name: status_bar_control
description: Status Bar Control, lets you control the status bar color, style (theme), visibility, and translucent properties across iOS and Android.
version: 3.2.1
homepage: https://github.com/rafaelmaeuer/flutter_statusbar_control

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.12.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.foo.statusbarcontrol
        pluginClass: StatusBarControlPlugin
      ios:
        pluginClass: StatusBarControlPlugin
